/* ============================================================
   מישמיש — _build-data.js
   ------------------------------------------------------------
   מטמיע את data/*.json לתוך src/js/data.js כ-window.MISHMISH_DATA.
   נחוץ כי file:// חוסם fetch() (CORS). הרצה ידנית:
       node src/js/_build-data.js
   הפלט (data.js) מחויב ל-git ומסומן AUTO-GENERATED.
   (מבוסס על lumi/app/js/_build-data.js)
   ============================================================ */
const fs = require('fs');
const path = require('path');

const root = path.resolve(__dirname, '..', '..');       // mishmish/
const dataDir = path.join(root, 'data');
const out = path.join(__dirname, 'data.js');

function readJson(name) {
  return JSON.parse(fs.readFileSync(path.join(dataDir, name), 'utf8'));
}

// כל pack-*.json = חבילת-תוכן; instructions-he.json = i18n יעד
const packs = fs.readdirSync(dataDir)
  .filter(f => f.startsWith('pack-') && f.endsWith('.json'))
  .sort()
  .map(readJson);

const DATA = {
  instructions: readJson('instructions-he.json'),
  packs,
  scaffold: readJson('scaffold.json'),   // שכבת שפת-הישרדות הרוחבית (F1) → MishmishScaffold
};

const banner =
  '/* AUTO-GENERATED by _build-data.js — do not edit by hand.\n' +
  '   מקור: mishmish/data/*.json. להרצה מחדש: node src/js/_build-data.js */\n';

fs.writeFileSync(out, banner + 'window.MISHMISH_DATA = ' + JSON.stringify(DATA, null, 2) + ';\n', 'utf8');
console.log('wrote', path.relative(root, out), '·', packs.length, 'pack(s)');
