/* ============================================================
   מישמיש — _build-data.js
   ------------------------------------------------------------
   מטמיע את data/*.json לתוך src/js/data.js כ-window.MISHMISH_DATA.
   נחוץ כי file:// חוסם fetch() (CORS). הרצה ידנית:
       node src/js/_build-data.js
   הפלט (data.js) מחויב ל-git ומסומן AUTO-GENERATED.
   (מבוסס על lumi/app/js/_build-data.js)
   ============================================================ */
const fs = require('fs');
const path = require('path');

const root = path.resolve(__dirname, '..', '..');       // mishmish/
const dataDir = path.join(root, 'data');
const out = path.join(__dirname, 'data.js');
const audioManifestPath = path.join(root, 'assets', 'audio', 'manifest.json');

function readJson(name) {
  return JSON.parse(fs.readFileSync(path.join(dataDir, name), 'utf8'));
}

// כל pack-*.json = חבילת-תוכן; instructions-he.json = i18n יעד
const packs = fs.readdirSync(dataDir)
  .filter(f => f.startsWith('pack-') && f.endsWith('.json'))
  .sort()
  .map(readJson);

const DATA = {
  instructions: readJson('instructions-he.json'),
  packs,
  scaffold: readJson('scaffold.json'),   // שכבת שפת-הישרדות הרוחבית (F1) → MishmishScaffold
  classPlan: readJson('class-plan.json'),// חצי A: מקור-אמת ל"נושא הכיתה עכשיו" → MishmishClassPlan
};

// מפת-האודיו (assets/audio/manifest.json) — מוטבעת גם היא כדי לשרוד file://
// (fetch נכשל שם ב-CORS, בדיוק כמו הדאטה). audio.js זורע ממנה את manifestMap
// באתחול, כך שכל מכניקה מקבלת קליפים מוקלטים מקומית — לא רק דפים עם setClipMap ידני.
let audioManifest = {};
try {
  audioManifest = JSON.parse(fs.readFileSync(audioManifestPath, 'utf8'));
} catch (e) {
  console.warn('audio manifest missing/unreadable — audio ייפול ל-TTS:', e.message);
}

const banner =
  '/* AUTO-GENERATED by _build-data.js — do not edit by hand.\n' +
  '   מקור: mishmish/data/*.json + assets/audio/manifest.json. להרצה מחדש: node src/js/_build-data.js */\n';

fs.writeFileSync(out,
  banner +
  'window.MISHMISH_DATA = ' + JSON.stringify(DATA, null, 2) + ';\n' +
  'window.MISHMISH_AUDIO_MANIFEST = ' + JSON.stringify(audioManifest, null, 2) + ';\n',
  'utf8');
console.log('wrote', path.relative(root, out), '·', packs.length, 'pack(s) ·',
  Object.keys(audioManifest).length, 'audio clip(s)');
