/* AUTO-GENERATED by _build-data.js — do not edit by hand.
   מקור: mishmish/data/*.json. להרצה מחדש: node src/js/_build-data.js */
window.MISHMISH_DATA = {
  "instructions": {
    "_comment": "פנייה לילד = לשון רבים (כלל נעול). עברית = יעד; מאומת ע\"י מיטל.",
    "listen_and_choose": {
      "he": "הַקְשִׁיבוּ וּבַחֲרוּ",
      "en_hint": "listen and choose"
    },
    "give_it": {
      "he": "תְּנוּ לְמִישְׁמִישׁ",
      "en_hint": "give it to mishmish"
    },
    "listen_again": {
      "he": "הַקְשִׁיבוּ שׁוּב",
      "en_hint": "listen again"
    },
    "light_and_find": {
      "he": "הָאִירוּ בַּפַּנָּס וּמִצְאוּ",
      "en_hint": "shine the lantern and find"
    }
  },
  "packs": [
    {
      "pack": "class",
      "_schema": "rich topic-pack per briefs/pack-schema.md §2 (meta/lexicon/patterns/contrasts/target). מזין את כל 6 המכניקות דרך target.<mechanic>. דאטה בלבד — אין קוד.",
      "_filename_note": "🔴 שם הקובץ = pack-CLASS.json (מקף), לא pack.class.json (נקודה) כפי שנכתב במשימה — כי _build-data.js מגלה packs ב-`f.startsWith('pack-')`. קובץ בנקודה היה נדלג בשקט ולא מגיע ל-runtime. תואם ל-pack-market.json / pack-mapping.json.",
      "_img_note": "img = נתיב יחסי מתחת ל-assets/items/ כולל סיומת (למשל 'class/item-sefer.png' → assets/items/class/item-sefer.png). מכניקה קוראת lexeme.img ומקדימה '../assets/items/'. (שים לב: lantern.js הישן מוסיף '.png' לבד ל-items[].options[].img — זה מבנה הפריטים הישן; ה-pack הזה הוא המבנה העשיר החדש עם lexicon.)",
      "_gates": "🔴 (א) כל עברית = טיוטה לאישור מיטל (asks.meytal). (ב) כל cognate_ar/audio_amiya = טיוטת עאמייה ar_verified:false → asks.native (tools/arabic-review-tool.html). ה-pack לא עובר done עד אישור בודק ילידי.",
      "meta": {
        "id": "class",
        "topic": "אֲנִי וְהַכִּתָּה",
        "topic_en": "me and my class · greetings & class objects",
        "week_range": "1-4 · ספטמבר 2026",
        "setting": "hara-courtyard",
        "bg": "bg-hara-courtyard.png",
        "space": "hara",
        "amir": true,
        "sound_wave": 1,
        "literacy_sight_words": [
          "אֲנִי",
          "כֵּן",
          "לֹא",
          "שָׁלוֹם"
        ],
        "cognate_focus": {
          "he": "שָׁלוֹם",
          "ar": "سلام",
          "ar_verified": false
        },
        "pb_focus_note": "מוקד פּ/בּ בגל 1 = קליל, שמיעתי-מודעות בלבד (בְּבַקָּשָׁה · פִּתְחוּ) — לא מוקד-הבחנה כבד."
      },
      "lexicon": [
        {
          "id": "machberet",
          "type": "object",
          "he": "מַחְבֶּרֶת",
          "gloss": "notebook",
          "img": "class/item-machberet.png",
          "emoji": "📓",
          "audio_he": "lex/machberet-he",
          "cognate_ar": "دفتر",
          "audio_amiya": "lex/machberet-amiya",
          "ar_verified": false,
          "gender": "f",
          "number": "sg",
          "sound_tags": [
            "b_p_free"
          ]
        },
        {
          "id": "machak",
          "type": "object",
          "he": "מַחַק",
          "gloss": "eraser",
          "img": "class/item-machak.png",
          "emoji": "🧽",
          "audio_he": "lex/machak-he",
          "cognate_ar": "محّاية",
          "audio_amiya": "lex/machak-amiya",
          "ar_verified": false,
          "gender": "m",
          "number": "sg",
          "sound_tags": [
            "b_p_free"
          ]
        },
        {
          "id": "kise",
          "type": "object",
          "he": "כִּסֵּא",
          "gloss": "chair",
          "img": "class/item-kise.png",
          "emoji": "🪑",
          "audio_he": "lex/kise-he",
          "cognate_ar": "كرسي",
          "audio_amiya": "lex/kise-amiya",
          "ar_verified": false,
          "gender": "m",
          "number": "sg",
          "sound_tags": [
            "b_p_free"
          ]
        },
        {
          "id": "yalkut",
          "type": "object",
          "he": "יַלְקוּט",
          "gloss": "schoolbag",
          "img": "class/item-yalkut.png",
          "emoji": "🎒",
          "audio_he": "lex/yalkut-he",
          "cognate_ar": "شنطة",
          "audio_amiya": "lex/yalkut-amiya",
          "ar_verified": false,
          "gender": "m",
          "number": "sg",
          "sound_tags": [
            "b_p_free"
          ]
        },
        {
          "id": "sefer",
          "type": "object",
          "he": "סֵפֶר",
          "gloss": "book",
          "img": "class/item-sefer.png",
          "emoji": "📖",
          "audio_he": "lex/sefer-he",
          "cognate_ar": "كتاب",
          "audio_amiya": "lex/sefer-amiya",
          "ar_verified": false,
          "_cognate_alt": "סֵפֶר ↔ سِفْر (sifr) = קוגנט-אמת (שורש ס-פ-ר), אך המילה היומיומית בעאמייה = كتاب. לבחירת הבודק הילידי.",
          "gender": "m",
          "number": "sg",
          "sound_tags": [
            "b_p_free"
          ]
        },
        {
          "id": "iparon",
          "type": "object",
          "he": "עִפָּרוֹן",
          "gloss": "pencil",
          "img": "class/item-iparon.png",
          "emoji": "✏️",
          "audio_he": "lex/iparon-he",
          "cognate_ar": "قلم",
          "audio_amiya": "lex/iparon-amiya",
          "ar_verified": false,
          "gender": "m",
          "number": "sg",
          "sound_tags": [
            "p_medial"
          ],
          "_pb": "עִפָּרוֹן נושא פָּ (פּ דגושה) — עוגן צליל /p/ לגל 1."
        },
        {
          "id": "shalom",
          "type": "greeting",
          "he": "שָׁלוֹם",
          "gloss": "hello / peace",
          "img": null,
          "emoji": "👋",
          "audio_he": "lex/shalom-he",
          "cognate_ar": "سلام",
          "audio_amiya": "lex/shalom-amiya",
          "ar_verified": false,
          "_cognate": "🔗 קוגנט-הליבה של נושא 1: שָׁלוֹם ↔ سلام (שורש ש/ס-ל-מ). לחישת-הגשר של אמיר.",
          "gender": null,
          "number": null,
          "sound_tags": [
            "b_p_free"
          ]
        },
        {
          "id": "toda",
          "type": "greeting",
          "he": "תּוֹדָה",
          "gloss": "thank you",
          "img": null,
          "emoji": "🙏",
          "audio_he": "lex/toda-he",
          "cognate_ar": "شكراً",
          "audio_amiya": "lex/toda-amiya",
          "ar_verified": false,
          "gender": null,
          "number": null,
          "sound_tags": [
            "b_p_free"
          ]
        },
        {
          "id": "bevakasha",
          "type": "greeting",
          "he": "בְּבַקָּשָׁה",
          "gloss": "please / you're welcome",
          "img": null,
          "emoji": "🤲",
          "audio_he": "lex/bevakasha-he",
          "cognate_ar": "لو سمحت",
          "audio_amiya": "lex/bevakasha-amiya",
          "ar_verified": false,
          "gender": null,
          "number": null,
          "sound_tags": [
            "b_initial"
          ],
          "_pb": "בְּבַקָּשָׁה נושאת בְּ ראשונית (בּ דגושה) — עוגן צליל /b/ מול פִּתְחוּ."
        }
      ],
      "patterns": [
        {
          "id": "greet",
          "frame": "שָׁלוֹם · מַה שְּׁלוֹמְכֶם?",
          "intent": "לְבָרֵךְ",
          "structure": "ברכת-מפגש",
          "slots": [
            "shalom",
            "toda",
            "bevakasha"
          ],
          "audio_frame": "pat/greet",
          "reply_frames": [
            "שָׁלוֹם!",
            "תּוֹדָה, טוֹב!"
          ],
          "recurs_in": [
            "class",
            "family",
            "play"
          ],
          "_note": "ברכה + שאלת-שלום בלשון רבים (מַה שְּׁלוֹמְכֶם). פנייה לילד תמיד רבים."
        },
        {
          "id": "this_that",
          "frame": "זֶה ___",
          "intent": "לְהַצְבִּיעַ / לְזַהוֹת",
          "structure": "זה + שם-עצם",
          "gendered": true,
          "frame_f": "זֹאת ___",
          "slots": [
            "machberet",
            "machak",
            "kise",
            "yalkut",
            "sefer",
            "iparon"
          ],
          "audio_frame": "pat/this-that",
          "recurs_in": [
            "class",
            "family",
            "food"
          ],
          "_note": "ציר מין: 'זֶה סֵפֶר' (m) מול 'זֹאת מַחְבֶּרֶת' (f) — מזין grammar-toggle."
        },
        {
          "id": "what_is",
          "frame": "מַה זֶּה?",
          "intent": "לִשְׁאוֹל",
          "structure": "שאלת-זיהוי",
          "slots": [
            "machberet",
            "machak",
            "kise",
            "yalkut",
            "sefer",
            "iparon"
          ],
          "audio_frame": "pat/what-is",
          "answer_pattern": "this_that",
          "recurs_in": [
            "class",
            "food",
            "colors"
          ],
          "_note": "שאלה → תשובת מילה/שתיים ('זֶה עִפָּרוֹן'). זוג עם this_that ל-roleplay."
        },
        {
          "id": "open_close",
          "frame": "פִּתְחוּ אֶת הַ___ · סִגְרוּ אֶת הַ___",
          "intent": "לְהוֹרוֹת",
          "structure": "הוראה קצרה (ציווי רבים)",
          "slots": [
            "sefer",
            "yalkut"
          ],
          "extra_targets": [
            "דֶּלֶת"
          ],
          "audio_frame": "pat/open-close",
          "recurs_in": [
            "class"
          ],
          "_note": "הוראות פשוטות מהברִיף: 'פִּתְחוּ אֶת הַסֵּפֶר' (נושאת פִּ) · 'סִגְרוּ אֶת הַדֶּלֶת'. מזין follow-instr. הַדֶּלֶת אין לה נכס-תמונה עדיין (asks.meytal)."
        }
      ],
      "contrasts": [
        {
          "pair": [
            "בְּ",
            "פִּ"
          ],
          "words": [
            [
              "בְּבַקָּשָׁה",
              "פִּתְחוּ"
            ]
          ],
          "lex_refs": [
            "bevakasha",
            "iparon"
          ],
          "wave": 1,
          "level": "gentle",
          "audio": [
            "con/bevakasha",
            "con/pitchu"
          ],
          "ar_verified": false,
          "_note": "זוג פּ/בּ הרשמי של נושא 1 (הברִיף: הפרעה = בבקשה · פִּתְחוּ). גל 1 = מודעות-שמע קלילה בלבד, לא הבחנה כבדה. אודיו חייב להישמע מובחן (QA תמלול Whisper). 🔴 לאישור מיטל."
        }
      ],
      "target": {
        "swim-hunt": "audioWord → lexeme.img",
        "same-different": "contrast.pair discrimination",
        "missing-slot": "pattern.frame → choose slot",
        "grammar-toggle": "lexeme.gender/number match (זֶה/זֹאת)",
        "follow-instr": "pattern open_close verb + lexeme (פִּתְחוּ/סִגְרוּ)",
        "roleplay": "pattern.frame produced to Amir (מַה זֶּה? → זֶה ___)"
      },
      "_mechanic_reads": {
        "swim-hunt": "lexicon (objects, img) + target.swim-hunt — זיהוי-בשמיעה פר-lexeme",
        "same-different": "contrasts — הבחנת בְּ/פִּ",
        "missing-slot": "patterns (this_that/greet) — בחירת slot",
        "grammar-toggle": "lexicon.gender/number + pattern this_that (זֶה/זֹאת)",
        "follow-instr": "pattern open_close + lexicon — ביצוע הוראה",
        "roleplay": "patterns what_is+this_that + amir — turn דו-לשוני"
      }
    },
    {
      "pack": "mapping",
      "mechanic": "lantern",
      "place": {
        "he": "בֶּחָצֵר בָּעֶרֶב",
        "ar": "بالحارة",
        "ar_verified": false
      },
      "topic": "placement",
      "pattern": "mapping",
      "pattern_he": "מִיפּוּי · הַכָּרַת מִלִּים בְּשֵׁמַע",
      "target": {
        "lantern": "audioWord → option.img"
      },
      "_target_note": "target = שדה גנרי פר-מכניקה (pack-schema §2). ה-loader חושף target[mechanic]; כל מכניקה קוראת אחיד.",
      "_note": "משחקון-המיפוי (הפרקטיס הראשון, חובה). מכניקת 'פנס' — השראה מ-stage-3-flashlight-demo של אבני יסוד. המטרה שוּנתה מ'מתחיל באות' ל'התמונה ששמעת את שמה' (audioWord→img). שמיעתי-קודם; בלי אדום/ירוק; ניקוד; עברית מאומתת ע\"י מיטל. probe שקט — הפלט = snapshot ל-BKT.",
      "items": [
        {
          "id": "map.mishmish.01",
          "dimension": "recognize",
          "target": "apricot",
          "measured": true,
          "pb_focus": false,
          "prompt": {
            "he": "מִשְׁמֵשׁ",
            "audio_he": "משמש",
            "instruction_key": "light_and_find"
          },
          "options": [
            {
              "item": "apricot",
              "emoji": "🍑",
              "img": "food/item-orange",
              "cap": "מִשְׁמֵשׁ",
              "correct": true
            },
            {
              "item": "cat",
              "emoji": "🐱",
              "cap": "חָתוּל",
              "correct": false
            },
            {
              "item": "dog",
              "emoji": "🐶",
              "cap": "כֶּלֶב",
              "correct": false
            }
          ],
          "help_he": "מִישְׁמִישׁ מְחַפֵּשׂ מִשְׁמֵשׁ 🍑"
        },
        {
          "id": "map.cat.01",
          "dimension": "recognize",
          "target": "cat",
          "measured": true,
          "pb_focus": false,
          "prompt": {
            "he": "חָתוּל",
            "audio_he": "חתול",
            "instruction_key": "light_and_find"
          },
          "options": [
            {
              "item": "cat",
              "emoji": "🐱",
              "cap": "חָתוּל",
              "correct": true
            },
            {
              "item": "bird",
              "emoji": "🐦",
              "cap": "צִפּוֹר",
              "correct": false
            },
            {
              "item": "dog",
              "emoji": "🐶",
              "cap": "כֶּלֶב",
              "correct": false
            }
          ],
          "help_he": "מִישְׁמִישׁ מְחַפֵּשׂ חָתוּל 🐱"
        },
        {
          "id": "map.banana.01",
          "dimension": "recognize",
          "target": "banana",
          "measured": true,
          "pb_focus": true,
          "_pb": "בָּנָנָה (בּ) מול פַּרְפַּר (פּ) — הבחנת פּ/בּ, מוקד הפרעה #1",
          "prompt": {
            "he": "בָּנָנָה",
            "audio_he": "בננה",
            "instruction_key": "light_and_find"
          },
          "options": [
            {
              "item": "banana",
              "emoji": "🍌",
              "img": "food/item-banana",
              "cap": "בָּנָנָה",
              "correct": true
            },
            {
              "item": "butterfly",
              "emoji": "🦋",
              "cap": "פַּרְפַּר",
              "correct": false
            },
            {
              "item": "apple",
              "emoji": "🍎",
              "img": "food/item-apple",
              "cap": "תַּפּוּחַ",
              "correct": false
            }
          ],
          "help_he": "מִישְׁמִישׁ מְחַפֵּשׂ בָּנָנָה 🍌"
        },
        {
          "id": "map.perach.01",
          "dimension": "recognize",
          "target": "flower",
          "measured": true,
          "pb_focus": true,
          "_pb": "פֶּרַח (פּ) מול בַּיִת (בּ) — הבחנת פּ/בּ הפוכה",
          "prompt": {
            "he": "פֶּרַח",
            "audio_he": "פרח",
            "instruction_key": "light_and_find"
          },
          "options": [
            {
              "item": "flower",
              "emoji": "🌸",
              "cap": "פֶּרַח",
              "correct": true
            },
            {
              "item": "house",
              "emoji": "🏠",
              "cap": "בַּיִת",
              "correct": false
            },
            {
              "item": "ball",
              "emoji": "⚽",
              "cap": "כַּדּוּר",
              "correct": false
            }
          ],
          "help_he": "מִישְׁמִישׁ מְחַפֵּשׂ פֶּרַח 🌸"
        },
        {
          "id": "map.panas.01",
          "dimension": "recognize",
          "target": "lantern",
          "measured": true,
          "pb_focus": false,
          "prompt": {
            "he": "פָּנָס",
            "audio_he": "פנס",
            "instruction_key": "light_and_find"
          },
          "options": [
            {
              "item": "lantern",
              "emoji": "🏮",
              "cap": "פָּנָס",
              "correct": true
            },
            {
              "item": "water",
              "emoji": "💧",
              "cap": "מַיִם",
              "correct": false
            },
            {
              "item": "star",
              "emoji": "⭐",
              "cap": "כּוֹכָב",
              "correct": false
            }
          ],
          "help_he": "מִישְׁמִישׁ מְחַפֵּשׂ פָּנָס 🏮"
        },
        {
          "id": "map.tzipor.01",
          "dimension": "recognize",
          "target": "bird",
          "measured": true,
          "pb_focus": false,
          "prompt": {
            "he": "צִפּוֹר",
            "audio_he": "ציפור",
            "instruction_key": "light_and_find"
          },
          "options": [
            {
              "item": "bird",
              "emoji": "🐦",
              "cap": "צִפּוֹר",
              "correct": true
            },
            {
              "item": "fish",
              "emoji": "🐟",
              "cap": "דָּג",
              "correct": false
            },
            {
              "item": "tree",
              "emoji": "🌳",
              "cap": "עֵץ",
              "correct": false
            }
          ],
          "help_he": "מִישְׁמִישׁ מְחַפֵּשׂ צִפּוֹר 🐦"
        },
        {
          "id": "map.frame.this_that.01",
          "pattern": "this_that",
          "dimension": "recognize",
          "target": "sefer",
          "measured": true,
          "pb_focus": false,
          "prompt": {
            "he": "זֶה סֵפֶר",
            "audio_he": "זה ספר",
            "instruction_key": "light_and_find"
          },
          "options": [
            {
              "item": "sefer",
              "emoji": "📖",
              "img": "class/item-sefer",
              "cap": "סֵפֶר",
              "correct": true
            },
            {
              "item": "machberet",
              "emoji": "📓",
              "img": "class/item-machberet",
              "cap": "מַחְבֶּרֶת",
              "correct": false
            },
            {
              "item": "kise",
              "emoji": "🪑",
              "img": "class/item-kise",
              "cap": "כִּסֵּא",
              "correct": false
            }
          ],
          "help_he": "מִישְׁמִישׁ אוֹמֵר: זֶה סֵפֶר 📖"
        },
        {
          "id": "map.frame.this_that.02",
          "pattern": "this_that",
          "dimension": "recognize",
          "target": "machberet",
          "measured": true,
          "pb_focus": false,
          "prompt": {
            "he": "זֹאת מַחְבֶּרֶת",
            "audio_he": "זאת מחברת",
            "instruction_key": "light_and_find"
          },
          "options": [
            {
              "item": "machberet",
              "emoji": "📓",
              "img": "class/item-machberet",
              "cap": "מַחְבֶּרֶת",
              "correct": true
            },
            {
              "item": "sefer",
              "emoji": "📖",
              "img": "class/item-sefer",
              "cap": "סֵפֶר",
              "correct": false
            },
            {
              "item": "iparon",
              "emoji": "✏️",
              "img": "class/item-iparon",
              "cap": "עִפָּרוֹן",
              "correct": false
            }
          ],
          "help_he": "מִישְׁמִישׁ אוֹמֵר: זֹאת מַחְבֶּרֶת 📓"
        },
        {
          "id": "map.frame.have.01",
          "pattern": "have",
          "dimension": "recognize",
          "target": "ball",
          "measured": true,
          "pb_focus": false,
          "prompt": {
            "he": "יֵשׁ לִי כַּדּוּר",
            "audio_he": "יש לי כדור",
            "instruction_key": "light_and_find"
          },
          "options": [
            {
              "item": "ball",
              "emoji": "⚽",
              "cap": "כַּדּוּר",
              "correct": true
            },
            {
              "item": "sefer",
              "emoji": "📖",
              "img": "class/item-sefer",
              "cap": "סֵפֶר",
              "correct": false
            },
            {
              "item": "apple",
              "emoji": "🍎",
              "img": "food/item-apple",
              "cap": "תַּפּוּחַ",
              "correct": false
            }
          ],
          "help_he": "מִישְׁמִישׁ אוֹמֵר: יֵשׁ לִי כַּדּוּר ⚽"
        },
        {
          "id": "map.frame.have.02",
          "pattern": "have",
          "dimension": "recognize",
          "target": "sefer",
          "measured": true,
          "pb_focus": false,
          "prompt": {
            "he": "יֵשׁ לִי סֵפֶר",
            "audio_he": "יש לי ספר",
            "instruction_key": "light_and_find"
          },
          "options": [
            {
              "item": "sefer",
              "emoji": "📖",
              "img": "class/item-sefer",
              "cap": "סֵפֶר",
              "correct": true
            },
            {
              "item": "ball",
              "emoji": "⚽",
              "cap": "כַּדּוּר",
              "correct": false
            },
            {
              "item": "banana",
              "emoji": "🍌",
              "img": "food/item-banana",
              "cap": "בָּנָנָה",
              "correct": false
            }
          ],
          "help_he": "מִישְׁמִישׁ אוֹמֵר: יֵשׁ לִי סֵפֶר 📖"
        },
        {
          "id": "map.frame.want.01",
          "pattern": "want",
          "dimension": "recognize",
          "target": "banana",
          "measured": true,
          "pb_focus": false,
          "prompt": {
            "he": "אֲנִי רוֹצֶה בָּנָנָה",
            "audio_he": "אני רוצה בננה",
            "instruction_key": "light_and_find"
          },
          "options": [
            {
              "item": "banana",
              "emoji": "🍌",
              "img": "food/item-banana",
              "cap": "בָּנָנָה",
              "correct": true
            },
            {
              "item": "apple",
              "emoji": "🍎",
              "img": "food/item-apple",
              "cap": "תַּפּוּחַ",
              "correct": false
            },
            {
              "item": "apricot",
              "emoji": "🍑",
              "img": "food/item-orange",
              "cap": "מִשְׁמֵשׁ",
              "correct": false
            }
          ],
          "help_he": "מִישְׁמִישׁ אוֹמֵר: אֲנִי רוֹצֶה בָּנָנָה 🍌"
        },
        {
          "id": "map.frame.want.02",
          "pattern": "want",
          "dimension": "recognize",
          "target": "apple",
          "measured": true,
          "pb_focus": false,
          "prompt": {
            "he": "אֲנִי רוֹצֶה תַּפּוּחַ",
            "audio_he": "אני רוצה תפוח",
            "instruction_key": "light_and_find"
          },
          "options": [
            {
              "item": "apple",
              "emoji": "🍎",
              "img": "food/item-apple",
              "cap": "תַּפּוּחַ",
              "correct": true
            },
            {
              "item": "banana",
              "emoji": "🍌",
              "img": "food/item-banana",
              "cap": "בָּנָנָה",
              "correct": false
            },
            {
              "item": "apricot",
              "emoji": "🍑",
              "img": "food/item-orange",
              "cap": "מִשְׁמֵשׁ",
              "correct": false
            }
          ],
          "help_he": "מִישְׁמִישׁ אוֹמֵר: אֲנִי רוֹצֶה תַּפּוּחַ 🍎"
        },
        {
          "id": "map.frame.give_me.01",
          "pattern": "give_me",
          "dimension": "recognize",
          "target": "apricot",
          "measured": true,
          "pb_focus": false,
          "prompt": {
            "he": "תֵּן לִי מִשְׁמֵשׁ",
            "audio_he": "תן לי משמש",
            "instruction_key": "light_and_find"
          },
          "options": [
            {
              "item": "apricot",
              "emoji": "🍑",
              "img": "food/item-orange",
              "cap": "מִשְׁמֵשׁ",
              "correct": true
            },
            {
              "item": "flower",
              "emoji": "🌸",
              "cap": "פֶּרַח",
              "correct": false
            },
            {
              "item": "bird",
              "emoji": "🐦",
              "cap": "צִפּוֹר",
              "correct": false
            }
          ],
          "help_he": "מִישְׁמִישׁ אוֹמֵר: תֵּן לִי מִשְׁמֵשׁ 🍑"
        },
        {
          "id": "map.frame.give_me.02",
          "pattern": "give_me",
          "dimension": "recognize",
          "target": "flower",
          "measured": true,
          "pb_focus": false,
          "prompt": {
            "he": "תֵּן לִי פֶּרַח",
            "audio_he": "תן לי פרח",
            "instruction_key": "light_and_find"
          },
          "options": [
            {
              "item": "flower",
              "emoji": "🌸",
              "cap": "פֶּרַח",
              "correct": true
            },
            {
              "item": "apricot",
              "emoji": "🍑",
              "img": "food/item-orange",
              "cap": "מִשְׁמֵשׁ",
              "correct": false
            },
            {
              "item": "cat",
              "emoji": "🐱",
              "cap": "חָתוּל",
              "correct": false
            }
          ],
          "help_he": "מִישְׁמִישׁ אוֹמֵר: תֵּן לִי פֶּרַח 🌸"
        },
        {
          "id": "map.frame.see_hear.01",
          "pattern": "see_hear",
          "dimension": "recognize",
          "target": "bird",
          "measured": true,
          "pb_focus": false,
          "prompt": {
            "he": "אֲנִי רוֹאֶה צִפּוֹר",
            "audio_he": "אני רואה ציפור",
            "instruction_key": "light_and_find"
          },
          "options": [
            {
              "item": "bird",
              "emoji": "🐦",
              "cap": "צִפּוֹר",
              "correct": true
            },
            {
              "item": "cat",
              "emoji": "🐱",
              "cap": "חָתוּל",
              "correct": false
            },
            {
              "item": "dog",
              "emoji": "🐶",
              "cap": "כֶּלֶב",
              "correct": false
            }
          ],
          "help_he": "מִישְׁמִישׁ אוֹמֵר: אֲנִי רוֹאֶה צִפּוֹר 🐦"
        },
        {
          "id": "map.frame.see_hear.02",
          "pattern": "see_hear",
          "dimension": "recognize",
          "target": "cat",
          "measured": true,
          "pb_focus": false,
          "prompt": {
            "he": "אֲנִי רוֹאֶה חָתוּל",
            "audio_he": "אני רואה חתול",
            "instruction_key": "light_and_find"
          },
          "options": [
            {
              "item": "cat",
              "emoji": "🐱",
              "cap": "חָתוּל",
              "correct": true
            },
            {
              "item": "bird",
              "emoji": "🐦",
              "cap": "צִפּוֹר",
              "correct": false
            },
            {
              "item": "fish",
              "emoji": "🐟",
              "cap": "דָּג",
              "correct": false
            }
          ],
          "help_he": "מִישְׁמִישׁ אוֹמֵר: אֲנִי רוֹאֶה חָתוּל 🐱"
        }
      ],
      "_frames_note": "🔴 6 הפריטים הראשונים = אוצר-מילים (pattern:'mapping'); 10 הפריטים האחרונים (map.frame.*) = פריטי-מסגרת שנוספו 14.7 לזריעת נקודת-התחלה פר-תבנית: 2 פר-תבנית-שדרה (this_that/have/want/give_me/see_hear), מתוייגים pattern:<שדרה>+dimension:recognize → lantern.js שולח ל-BKT את ה-KC האמיתי וזורע L1 (identifies). 2 מילות-יעד שונות פר-תבנית → מאפשר גם 'נרכשה' (סף ≥2 נכונות · ≥2 מילים). כל העברית מנוקדת = טיוטה לאישור מיטל; רק נכסים/אמוג'י קיימים. הערה-אורך: המיפוי כעת 16 פריטים — אם ארוך מדי לגיל, אפשר לצמצם ל-1 פר-תבנית (זורע 'emerging' לא 'נרכשה')."
    },
    {
      "pack": "market",
      "mechanic": "give-me",
      "place": {
        "he": "בַּשּׁוּק",
        "ar": "بالسوق",
        "ar_verified": false
      },
      "topic": "food",
      "pattern": "give_me",
      "pattern_he": "תֵּן לִי ___",
      "target": {
        "give-me": "audioPhrase → item.img"
      },
      "_target_note": "target = שדה גנרי פר-מכניקה (pack-schema §2). ה-loader חושף target[mechanic]; כל מכניקה קוראת אחיד.",
      "_note": "הנושא = תפאורה; ציר-הרכישה = התבנית 'תן לי ___' (כוונת-בקשה). עברית מאומתת ע\"י מיטל; כל help_ar = טיוטה, לא-מאושר עד בודק ילידי.",
      "items": [
        {
          "id": "market.food.give.tapuz.01",
          "dimension": "recognize",
          "target": "tapuz",
          "measured": true,
          "pb_focus": false,
          "prompt": {
            "he": "תֵּן לִי תַּפּוּז",
            "audio_he": "תן לי תפוז",
            "instruction_key": "listen_and_choose"
          },
          "options": [
            {
              "item": "orange",
              "img": "item-orange",
              "cap": "תַּפּוּז",
              "correct": true
            },
            {
              "item": "apple",
              "img": "item-apple",
              "cap": "תַּפּוּחַ",
              "correct": false
            },
            {
              "item": "banana",
              "img": "item-banana",
              "cap": "בָּנָנָה",
              "correct": false
            }
          ],
          "help_he": "מִישְׁמִישׁ מְחַפֵּשׂ תַּפּוּז",
          "help_ar": "مشمش بدّه برتقالة",
          "help_ar_verified": false
        },
        {
          "id": "market.food.give.banana.01",
          "dimension": "recognize",
          "target": "banana",
          "measured": true,
          "pb_focus": true,
          "_pb": "בָּנָנָה (בּ) מול תַּפּוּז (פּ) — הבחנת פּ/בּ, מוקד הפרעה #1",
          "prompt": {
            "he": "תֵּן לִי בָּנָנָה",
            "audio_he": "תן לי בננה",
            "instruction_key": "listen_and_choose"
          },
          "options": [
            {
              "item": "banana",
              "img": "item-banana",
              "cap": "בָּנָנָה",
              "correct": true
            },
            {
              "item": "orange",
              "img": "item-orange",
              "cap": "תַּפּוּז",
              "correct": false
            },
            {
              "item": "apple",
              "img": "item-apple",
              "cap": "תַּפּוּחַ",
              "correct": false
            }
          ],
          "help_he": "מִישְׁמִישׁ מְחַפֵּשׂ בָּנָנָה",
          "help_ar": "مشمش بدّه موزة",
          "help_ar_verified": false
        },
        {
          "id": "market.food.give.tapuach.01",
          "dimension": "recognize",
          "target": "tapuach",
          "measured": true,
          "pb_focus": false,
          "prompt": {
            "he": "תֵּן לִי תַּפּוּחַ",
            "audio_he": "תן לי תפוח",
            "instruction_key": "listen_and_choose"
          },
          "options": [
            {
              "item": "apple",
              "img": "item-apple",
              "cap": "תַּפּוּחַ",
              "correct": true
            },
            {
              "item": "banana",
              "img": "item-banana",
              "cap": "בָּנָנָה",
              "correct": false
            },
            {
              "item": "orange",
              "img": "item-orange",
              "cap": "תַּפּוּז",
              "correct": false
            }
          ],
          "help_he": "מִישְׁמִישׁ מְחַפֵּשׂ תַּפּוּחַ",
          "help_ar": "مشمش بدّه تفاحة",
          "help_ar_verified": false
        }
      ]
    }
  ],
  "scaffold": {
    "_comment": "שכבת שפת-הישרדות רוחבית — מקור-אמת יחיד, זמין-תמיד בכל מסך. (F1) התבנית=קוד (js/shared/scaffold.js); הקובץ הזה=דאטה. אסור לשכפל את השורה בקוד-מכניקה — כל משחקון מזריק מכאן. עברית=יעד (מאומת מיטל); ערבית=פיגום עאמייה, טיוטה לא-מאושרת (ar_verified:false) עד בודק ילידי דרך tools/arabic-review-tool.html.",
    "survival_bar": {
      "_note": "3 כפתורי-הישרדות. action+arg מתמפים ל-API של המשחקון הפעיל: replay(false)=עוד-פעם, replay(true)=לאט, hint()=לא-הבנתי. ה-id חייב להישאר sv-again/sv-slow/sv-help — עליו נשענת חיווט המכניקות (play.js/lantern.js/measured.js).",
      "buttons": [
        {
          "id": "sv-again",
          "action": "replay",
          "arg": false,
          "emoji": "🔁",
          "icon": "icon-replay.svg",
          "label_he": "עוֹד פַּעַם"
        },
        {
          "id": "sv-slow",
          "action": "replay",
          "arg": true,
          "emoji": "🐢",
          "icon": "icon-slow.svg",
          "label_he": "לְאַט"
        },
        {
          "id": "sv-help",
          "action": "hint",
          "arg": null,
          "emoji": "❔",
          "icon": "icon-help.svg",
          "label_he": "לֹא הֵבַנְתִּי"
        }
      ]
    },
    "amir_hints": {
      "_note": "טקסטי-רמז גנריים של אמיר (דמות-עמית דו-לשונית) פר-מדרג — למכניקות עתידיות שאין להן תסריט-רמז משלהן. מדרג נעול: encourage (עידוד להאזין שוב) → point (הצבעה חזותית על הנכון) → amiya (פיגום עאמייה בשפת-האם). 🔴 he=טיוטה פדגוגית לאישור מיטל. 🔴 ar=טיוטת עאמייה לא-מאושרת: ar_verified:false, לא מוצג/מושמע כברירת-מחדל, נרשם ב-asks.native.",
      "tiers": [
        {
          "tier": "encourage",
          "_use": "שלב 0 — עידוד להאזין שוב, בלי לחשוף את התשובה.",
          "state": "listening",
          "he": "עוֹד פַּעַם — הַקְשִׁיבוּ טוֹב, אַתֶּם קְרוֹבִים!",
          "ar": "كمان مرّة — اسمعوا منيح، قرّبتوا!",
          "ar_verified": false
        },
        {
          "tier": "point",
          "_use": "שלב 1→2 — הפניה חזותית: מישמיש מראה איפה הנכון.",
          "state": "hint",
          "he": "הִסְתַּכְּלוּ — מִישְׁמִישׁ מַרְאֶה לָכֶם אֵיפֹה.",
          "ar": "تطلّعوا — مشمش بيوريكم وين.",
          "ar_verified": false
        },
        {
          "tier": "amiya",
          "_use": "שלב אחרון — פיגום-עאמייה: אמיר לוחש רמז בשפת-האם. מגודר עד אישור בודק ילידי.",
          "state": "hint",
          "he": "אָמִיר לוֹחֵשׁ לָכֶם בַּעֲרָבִית…",
          "ar": "أمير بيوشوشلكم بالعربي…",
          "ar_verified": false
        }
      ]
    }
  }
};
