/* AUTO-GENERATED by _build-data.js — do not edit by hand.
   מקור: mishmish/data/*.json. להרצה מחדש: node src/js/_build-data.js */
window.MISHMISH_DATA = {
  "instructions": {
    "_comment": "פנייה לילד = לשון רבים (כלל נעול). עברית = יעד; מאומת ע\"י מיטל.",
    "listen_and_choose": {
      "he": "הַקְשִׁיבוּ וּבַחֲרוּ",
      "en_hint": "listen and choose"
    },
    "give_it": {
      "he": "תְּנוּ לְמִישְׁמִישׁ",
      "en_hint": "give it to mishmish"
    },
    "listen_again": {
      "he": "הַקְשִׁיבוּ שׁוּב",
      "en_hint": "listen again"
    },
    "light_and_find": {
      "he": "הָאִירוּ בַּפַּנָּס וּמִצְאוּ",
      "en_hint": "shine the lantern and find"
    }
  },
  "packs": [
    {
      "pack": "mapping",
      "mechanic": "lantern",
      "place": {
        "he": "בֶּחָצֵר בָּעֶרֶב",
        "ar": "بالحارة",
        "ar_verified": false
      },
      "topic": "placement",
      "pattern": "mapping",
      "pattern_he": "מִיפּוּי · הַכָּרַת מִלִּים בְּשֵׁמַע",
      "target": {
        "lantern": "audioWord → option.img"
      },
      "_target_note": "target = שדה גנרי פר-מכניקה (pack-schema §2). ה-loader חושף target[mechanic]; כל מכניקה קוראת אחיד.",
      "_note": "משחקון-המיפוי (הפרקטיס הראשון, חובה). מכניקת 'פנס' — השראה מ-stage-3-flashlight-demo של אבני יסוד. המטרה שוּנתה מ'מתחיל באות' ל'התמונה ששמעת את שמה' (audioWord→img). שמיעתי-קודם; בלי אדום/ירוק; ניקוד; עברית מאומתת ע\"י מיטל. probe שקט — הפלט = snapshot ל-BKT.",
      "items": [
        {
          "id": "map.mishmish.01",
          "dimension": "recognize",
          "target": "apricot",
          "measured": true,
          "pb_focus": false,
          "prompt": {
            "he": "מִשְׁמֵשׁ",
            "audio_he": "משמש",
            "instruction_key": "light_and_find"
          },
          "options": [
            {
              "item": "apricot",
              "emoji": "🍑",
              "img": "food/item-orange",
              "cap": "מִשְׁמֵשׁ",
              "correct": true
            },
            {
              "item": "cat",
              "emoji": "🐱",
              "cap": "חָתוּל",
              "correct": false
            },
            {
              "item": "dog",
              "emoji": "🐶",
              "cap": "כֶּלֶב",
              "correct": false
            }
          ],
          "help_he": "מִישְׁמִישׁ מְחַפֵּשׂ מִשְׁמֵשׁ 🍑"
        },
        {
          "id": "map.cat.01",
          "dimension": "recognize",
          "target": "cat",
          "measured": true,
          "pb_focus": false,
          "prompt": {
            "he": "חָתוּל",
            "audio_he": "חתול",
            "instruction_key": "light_and_find"
          },
          "options": [
            {
              "item": "cat",
              "emoji": "🐱",
              "cap": "חָתוּל",
              "correct": true
            },
            {
              "item": "bird",
              "emoji": "🐦",
              "cap": "צִפּוֹר",
              "correct": false
            },
            {
              "item": "dog",
              "emoji": "🐶",
              "cap": "כֶּלֶב",
              "correct": false
            }
          ],
          "help_he": "מִישְׁמִישׁ מְחַפֵּשׂ חָתוּל 🐱"
        },
        {
          "id": "map.banana.01",
          "dimension": "recognize",
          "target": "banana",
          "measured": true,
          "pb_focus": true,
          "_pb": "בָּנָנָה (בּ) מול פַּרְפַּר (פּ) — הבחנת פּ/בּ, מוקד הפרעה #1",
          "prompt": {
            "he": "בָּנָנָה",
            "audio_he": "בננה",
            "instruction_key": "light_and_find"
          },
          "options": [
            {
              "item": "banana",
              "emoji": "🍌",
              "img": "food/item-banana",
              "cap": "בָּנָנָה",
              "correct": true
            },
            {
              "item": "butterfly",
              "emoji": "🦋",
              "cap": "פַּרְפַּר",
              "correct": false
            },
            {
              "item": "apple",
              "emoji": "🍎",
              "img": "food/item-apple",
              "cap": "תַּפּוּחַ",
              "correct": false
            }
          ],
          "help_he": "מִישְׁמִישׁ מְחַפֵּשׂ בָּנָנָה 🍌"
        },
        {
          "id": "map.perach.01",
          "dimension": "recognize",
          "target": "flower",
          "measured": true,
          "pb_focus": true,
          "_pb": "פֶּרַח (פּ) מול בַּיִת (בּ) — הבחנת פּ/בּ הפוכה",
          "prompt": {
            "he": "פֶּרַח",
            "audio_he": "פרח",
            "instruction_key": "light_and_find"
          },
          "options": [
            {
              "item": "flower",
              "emoji": "🌸",
              "cap": "פֶּרַח",
              "correct": true
            },
            {
              "item": "house",
              "emoji": "🏠",
              "cap": "בַּיִת",
              "correct": false
            },
            {
              "item": "ball",
              "emoji": "⚽",
              "cap": "כַּדּוּר",
              "correct": false
            }
          ],
          "help_he": "מִישְׁמִישׁ מְחַפֵּשׂ פֶּרַח 🌸"
        },
        {
          "id": "map.panas.01",
          "dimension": "recognize",
          "target": "lantern",
          "measured": true,
          "pb_focus": false,
          "prompt": {
            "he": "פָּנָס",
            "audio_he": "פנס",
            "instruction_key": "light_and_find"
          },
          "options": [
            {
              "item": "lantern",
              "emoji": "🏮",
              "cap": "פָּנָס",
              "correct": true
            },
            {
              "item": "water",
              "emoji": "💧",
              "cap": "מַיִם",
              "correct": false
            },
            {
              "item": "star",
              "emoji": "⭐",
              "cap": "כּוֹכָב",
              "correct": false
            }
          ],
          "help_he": "מִישְׁמִישׁ מְחַפֵּשׂ פָּנָס 🏮"
        },
        {
          "id": "map.tzipor.01",
          "dimension": "recognize",
          "target": "bird",
          "measured": true,
          "pb_focus": false,
          "prompt": {
            "he": "צִפּוֹר",
            "audio_he": "ציפור",
            "instruction_key": "light_and_find"
          },
          "options": [
            {
              "item": "bird",
              "emoji": "🐦",
              "cap": "צִפּוֹר",
              "correct": true
            },
            {
              "item": "fish",
              "emoji": "🐟",
              "cap": "דָּג",
              "correct": false
            },
            {
              "item": "tree",
              "emoji": "🌳",
              "cap": "עֵץ",
              "correct": false
            }
          ],
          "help_he": "מִישְׁמִישׁ מְחַפֵּשׂ צִפּוֹר 🐦"
        }
      ]
    },
    {
      "pack": "market",
      "mechanic": "give-me",
      "place": {
        "he": "בַּשּׁוּק",
        "ar": "بالسوق",
        "ar_verified": false
      },
      "topic": "food",
      "pattern": "give_me",
      "pattern_he": "תֵּן לִי ___",
      "target": {
        "give-me": "audioPhrase → item.img"
      },
      "_target_note": "target = שדה גנרי פר-מכניקה (pack-schema §2). ה-loader חושף target[mechanic]; כל מכניקה קוראת אחיד.",
      "_note": "הנושא = תפאורה; ציר-הרכישה = התבנית 'תן לי ___' (כוונת-בקשה). עברית מאומתת ע\"י מיטל; כל help_ar = טיוטה, לא-מאושר עד בודק ילידי.",
      "items": [
        {
          "id": "market.food.give.tapuz.01",
          "dimension": "recognize",
          "target": "tapuz",
          "measured": true,
          "pb_focus": false,
          "prompt": {
            "he": "תֵּן לִי תַּפּוּז",
            "audio_he": "תן לי תפוז",
            "instruction_key": "listen_and_choose"
          },
          "options": [
            {
              "item": "orange",
              "img": "item-orange",
              "cap": "תַּפּוּז",
              "correct": true
            },
            {
              "item": "apple",
              "img": "item-apple",
              "cap": "תַּפּוּחַ",
              "correct": false
            },
            {
              "item": "banana",
              "img": "item-banana",
              "cap": "בָּנָנָה",
              "correct": false
            }
          ],
          "help_he": "מִישְׁמִישׁ מְחַפֵּשׂ תַּפּוּז",
          "help_ar": "مشمش بدّه برتقالة",
          "help_ar_verified": false
        },
        {
          "id": "market.food.give.banana.01",
          "dimension": "recognize",
          "target": "banana",
          "measured": true,
          "pb_focus": true,
          "_pb": "בָּנָנָה (בּ) מול תַּפּוּז (פּ) — הבחנת פּ/בּ, מוקד הפרעה #1",
          "prompt": {
            "he": "תֵּן לִי בָּנָנָה",
            "audio_he": "תן לי בננה",
            "instruction_key": "listen_and_choose"
          },
          "options": [
            {
              "item": "banana",
              "img": "item-banana",
              "cap": "בָּנָנָה",
              "correct": true
            },
            {
              "item": "orange",
              "img": "item-orange",
              "cap": "תַּפּוּז",
              "correct": false
            },
            {
              "item": "apple",
              "img": "item-apple",
              "cap": "תַּפּוּחַ",
              "correct": false
            }
          ],
          "help_he": "מִישְׁמִישׁ מְחַפֵּשׂ בָּנָנָה",
          "help_ar": "مشمش بدّه موزة",
          "help_ar_verified": false
        },
        {
          "id": "market.food.give.tapuach.01",
          "dimension": "recognize",
          "target": "tapuach",
          "measured": true,
          "pb_focus": false,
          "prompt": {
            "he": "תֵּן לִי תַּפּוּחַ",
            "audio_he": "תן לי תפוח",
            "instruction_key": "listen_and_choose"
          },
          "options": [
            {
              "item": "apple",
              "img": "item-apple",
              "cap": "תַּפּוּחַ",
              "correct": true
            },
            {
              "item": "banana",
              "img": "item-banana",
              "cap": "בָּנָנָה",
              "correct": false
            },
            {
              "item": "orange",
              "img": "item-orange",
              "cap": "תַּפּוּז",
              "correct": false
            }
          ],
          "help_he": "מִישְׁמִישׁ מְחַפֵּשׂ תַּפּוּחַ",
          "help_ar": "مشمش بدّه تفاحة",
          "help_ar_verified": false
        }
      ]
    }
  ],
  "scaffold": {
    "_comment": "שכבת שפת-הישרדות רוחבית — מקור-אמת יחיד, זמין-תמיד בכל מסך. (F1) התבנית=קוד (js/shared/scaffold.js); הקובץ הזה=דאטה. אסור לשכפל את השורה בקוד-מכניקה — כל משחקון מזריק מכאן. עברית=יעד (מאומת מיטל); ערבית=פיגום עאמייה, טיוטה לא-מאושרת (ar_verified:false) עד בודק ילידי דרך tools/arabic-review-tool.html.",
    "survival_bar": {
      "_note": "3 כפתורי-הישרדות. action+arg מתמפים ל-API של המשחקון הפעיל: replay(false)=עוד-פעם, replay(true)=לאט, hint()=לא-הבנתי. ה-id חייב להישאר sv-again/sv-slow/sv-help — עליו נשענת חיווט המכניקות (play.js/lantern.js/measured.js).",
      "buttons": [
        {
          "id": "sv-again",
          "action": "replay",
          "arg": false,
          "emoji": "🔁",
          "icon": "icon-replay.svg",
          "label_he": "עוֹד פַּעַם"
        },
        {
          "id": "sv-slow",
          "action": "replay",
          "arg": true,
          "emoji": "🐢",
          "icon": "icon-slow.svg",
          "label_he": "לְאַט"
        },
        {
          "id": "sv-help",
          "action": "hint",
          "arg": null,
          "emoji": "❔",
          "icon": "icon-help.svg",
          "label_he": "לֹא הֵבַנְתִּי"
        }
      ]
    },
    "amir_hints": {
      "_note": "טקסטי-רמז גנריים של אמיר (דמות-עמית דו-לשונית) פר-מדרג — למכניקות עתידיות שאין להן תסריט-רמז משלהן. מדרג נעול: encourage (עידוד להאזין שוב) → point (הצבעה חזותית על הנכון) → amiya (פיגום עאמייה בשפת-האם). 🔴 he=טיוטה פדגוגית לאישור מיטל. 🔴 ar=טיוטת עאמייה לא-מאושרת: ar_verified:false, לא מוצג/מושמע כברירת-מחדל, נרשם ב-asks.native.",
      "tiers": [
        {
          "tier": "encourage",
          "_use": "שלב 0 — עידוד להאזין שוב, בלי לחשוף את התשובה.",
          "state": "listening",
          "he": "עוֹד פַּעַם — הַקְשִׁיבוּ טוֹב, אַתֶּם קְרוֹבִים!",
          "ar": "كمان مرّة — اسمعوا منيح، قرّبتوا!",
          "ar_verified": false
        },
        {
          "tier": "point",
          "_use": "שלב 1→2 — הפניה חזותית: מישמיש מראה איפה הנכון.",
          "state": "hint",
          "he": "הִסְתַּכְּלוּ — מִישְׁמִישׁ מַרְאֶה לָכֶם אֵיפֹה.",
          "ar": "تطلّعوا — مشمش بيوريكم وين.",
          "ar_verified": false
        },
        {
          "tier": "amiya",
          "_use": "שלב אחרון — פיגום-עאמייה: אמיר לוחש רמז בשפת-האם. מגודר עד אישור בודק ילידי.",
          "state": "hint",
          "he": "אָמִיר לוֹחֵשׁ לָכֶם בַּעֲרָבִית…",
          "ar": "أمير بيوشوشلكم بالعربي…",
          "ar_verified": false
        }
      ]
    }
  }
};
